### ISSUE TITLE
Small utility using libtimecode

### ISSUE THREAD

**Issue by zuzzurro** [x42/libtimecode#8]
Hi
I am writing a small utility that will be used to insert the current time of day in timecode format in ffmpeg. I have some comments about your library and I would like to know if you may be interested in them.

**Comment by x42** [comment]
I'll be happy to discuss if it helps to improve ffmpeg; but for all intents and purposes this library is pretty much dead.

**Comment by zuzzurro** [comment]
That's what I wanted to know. Do you happen to know if there exist something similar that can be used to replace it?

**Comment by zuzzurro** [comment]
Do you mind if I ask you a couple of questions to let me understand how I should proceed?
I have various options in front of me such as:
1) moving to another library
2) code my own ultra simplified version (no need for a library to do what I want most probably)
3) keep using this one and maybe adding some patches/code
4) fork it
5) just try and discussing with ffmpeg to add my needed functionality inside it

Thanks for your time and patience and direction

**Comment by x42** [comment]
The problem with 3,4 is that this library is not packaged by any major GNU/Linux distribution. That may not be an issue long term, but it will likely delay rollout of your patch to ffmpeg.

I don't know another library, so I cannot suggest 1. -- Although there probably is some code out there to fulfill your need.

2,5 are likely the easiest. I expect the harder parts with "time of day" will be to deal with timezones, not timecode  per se. You are also welcome to lift some relevant code for dropframe timecode from this lib.

**Comment by zuzzurro** [comment]
Let me jut explain what I'm trying to achieve. I created this small utility starting from your test app, I call it tcdate.c:

```
#include <stdio.h>
#include <string.h>
#include <inttypes.h>
#include <time.h>
#include <timecode/timecode.h>

int main (int argc, char **argv) {
	const TimecodeRate tcfpsNS      = {   1000000000,   1, 0, 1};
	char tcs[64];
	struct tm *tm;
	Timecode tc;
	struct timespec ts;

	memset(&tc, 0, sizeof(Timecode));

	clock_gettime(CLOCK_REALTIME, &ts);
	tm = localtime(&ts.tv_sec);

	tc.d.year     = tm->tm_year + 1900;
	tc.d.month    = tm->tm_mon + 1;
	tc.d.day      = tm->tm_mday;
	tc.d.timezone = 0;
	tc.t.hour     = tm->tm_hour;
	tc.t.minute   = tm->tm_min;
	tc.t.second   = tm->tm_sec;
	tc.t.frame    = ts.tv_nsec;
	tc.t.subframe = 0;

	timecode_copy_rate(&tc, &tcfpsNS);
	timecode_convert_rate(&tc.t, timecode_FPS25, &tc.t, &tcfpsNS);
	timecode_copy_rate(&tc, timecode_FPS25);
	timecode_strftimecode(tcs, 64,"%H\\\\:%M\\\\:%S\\\\:%F", &tc);

	fprintf(stdout, "%s\n", tcs);

	return 0;
}
```
And I'm using in ffmpeg like this:

`drawtext=: x=(w-tw)/2: y=h-(2*lh): timecode=$(tcdate): r=${frame_rate}:`

Of course this is extremely rough around the edges and I plan to eventually add switches to let me specify the strftime string and the frame rate.

I spend quite a bit of time looking at various forums and at the documentation but I cannot find a builtin way to achieve this in ffmpeg.

What do you think? The goal of course is to burn in the video the time of day with frames instead of milliseconds to let me easily check issues in the video.

**Comment by zuzzurro** [comment]
Forget it, I don't think this was a workable way to proceed since between the time the timecode is queried and it's actually used by the engine the time can vary a lot making this unreliable.
Thanks anyway
